function car=CarInit( x, y, th, dlt, v, a, j, L, W, WB, TR, Rmin, SteerMax )
    car.dt  = 0.1;
    car.x   = x;
    car.y   = y;
    car.s   = 0;
    car.th  = th;
    car.dlt = dlt;
    car.ddlt= 0;
    car.v   =  v;
    car.a   =  a;
    car.j   =  j;
    car.L   =  L;
    car.W   =  W;
    car.WB  =  WB;
    car.TR  =  TR;
    car.Rmin = Rmin;
    car.dltLim2 = WB/Rmin;
    %Rc = sqrt( WB^2 + (( sqrt( Rmin^2 - L^2 ) - (TR/2))^2));    
    Rc = sqrt((sqrt(Rmin^2 - WB^2)-TR/2)^2  + WB^2 );
    car.Rc = Rc;    
    car.dltLim = asin( WB / Rc );
    car.StLim = SteerMax;
end